# Generated by Django 4.1.13 on 2024-03-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_desc',
            new_name='receipe_description',
        ),
    ]
